# .travis.yml -- Travis CI specification file.
# Copyright 2016-2019 the Tectonic Project
# Licensed under the MIT License.

language: rust

cache: false

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
      env: RUSTFLAGS="-C link-dead-code"
    - os: osx
      osx_image: xcode10.2
      rust: nightly
    - os: windows
      rust: nightly
      env:
        - VS15=true
        - VCPKG_ROOT=${HOME}/vcpkg
        - VCPKG_DEFAULT_TRIPLET=x64-windows
        - TECTONIC_DEP_BACKEND=vcpkg
      script:
        - dist/install_vcpkg_win.bat
        - ${VCPKG_ROOT}/vcpkg install "harfbuzz[icu,graphite2]" "openssl" "fontconfig"
        - sh dist/travis.sh
      cache:
        directories:
          - ${VCPKG_ROOT}/installed


# Don't CI branches besides master. Pull requests still get CI'd -- but
# when a PR comes in on a branch in the same repo, this prevents it from
# being CI'd twice.
branches:
  only:
    - oxidize

addons:
  apt:
    packages:
      - libgraphite2-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
      - libicu-dev
      - libssl-dev
      - openssl
  homebrew:
    packages:
      - harfbuzz
      - openssl

install: true
script: source dist/travis.sh
