# .travis.yml -- Travis CI specification file.
# Copyright 2016-2019 the Tectonic Project
# Licensed under the MIT License.

language: rust

cache: false

matrix:
  include:
    # Linux, Rust stable: the "main" build; we do code coverage, AppImage generation, etc.
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
      env: RUSTFLAGS="-C link-dead-code"
    # MacOS, Rust stable: just a smoke test
    - os: osx
      osx_image: xcode10.2
      rust: nightly
    - os: windows
      rust: nightly
      env: VS15=true
      script: sh dist/travis.sh
  allow_failures:
    - os: windows

# Don't CI branches besides master. Pull requests still get CI'd -- but
# when a PR comes in on a branch in the same repo, this prevents it from
# being CI'd twice.
branches:
  only:
    - oxidize

addons:
  apt:
    packages:
      - libgraphite2-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
      - libicu-dev
      - libssl-dev
      - openssl
      - zlib1g-dev
  homebrew:
    packages:
      - harfbuzz
      - openssl

install: true
script: source dist/travis.sh
